### ISSUE TITLE
Peer-to-Peer Review for To-Do List.

### ISSUE THREAD

**Issue by ezraermy** [nxn404-n/To-Do-list#5]
- [ ] I found the code is compact and well organized. It looks awesome.
- [ ] As per the requirement of this project, it is recommended to use a filter rather than a splice at line 20 of class.js.
- [ ] As per the requirement of this project, all your javascript file has to be in src. This might create some problems with your webpack configuration.
